// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJf1X2ULIgaEc_huf5KuI541ng207ftho',
    appId: '1:619753913463:web:20adce3fbfd7e7c0915a72',
    messagingSenderId: '619753913463',
    projectId: 'todo-list-36f37',
    authDomain: 'todo-list-36f37.firebaseapp.com',
    storageBucket: 'todo-list-36f37.appspot.com',
    measurementId: 'G-0MX8CZ9VV8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNBs-ry85glNakLcwOg2yIGQkNyD8pKHo',
    appId: '1:619753913463:android:04c3606480baa205915a72',
    messagingSenderId: '619753913463',
    projectId: 'todo-list-36f37',
    storageBucket: 'todo-list-36f37.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOiRHnBBuDGePTv1UXSkWNbkPNCk_ZSkU',
    appId: '1:619753913463:ios:051bacd35d84cdaa915a72',
    messagingSenderId: '619753913463',
    projectId: 'todo-list-36f37',
    storageBucket: 'todo-list-36f37.appspot.com',
    iosClientId: '619753913463-g5b26rud1ve4f3fqhv8rpo3hjja04r1r.apps.googleusercontent.com',
    iosBundleId: 'com.derekdileo.todoFlutter',
  );
}
